name: ci cd

on:
  push:
      branches: ["main"]
      
jobs:
  CI:
      runs-on: ubuntu-latest
      
  step:
    - uses: actions/checkout@v4.1.1
      
    - name: autenticacao no docker hub    
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
        
  name: construçao de imagem docker
  uses: docker/build-push-action@v5.0.0
    with:
      context: ./src
      file: ./src/dockerfile
      push: true
      
      
            
      
          
    
    
