on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
  step:
    uses: actions/checkout@v4.1.1

    name: autenticacao no docker hub
    uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
    with:
      username: ${{secrets.DOCKERHUB_USER}}
      password: ${{secrets.DOCKERHUB_PWD}}
    
    name: construçao de imagem ddocker
    uses: docker/build-push-action@v5.0.0
    with:
      context: ./src
      file: ./src/dockerfile
      push: true
      
      
            
      
          
    
    
