name: CI-CD-NOVO
on: 
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: construcao da imagem docker
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/dockerfile
          push: true
      
      
      
            
      
          
    
    
